//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Box_v0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Exam
    {
        public int Std_ID { get; set; }
        public int E_ID { get; set; }
        public int Q_ID { get; set; }
        public string Std_Answer { get; set; }
        public Nullable<int> Q_Grade { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
